/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.springexample.servicebuilder.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import com.liferay.springexample.servicebuilder.service.persistence.JIRAActionPK;

import java.io.Serializable;

/**
 * The base model interface for the JIRAAction service. Represents a row in the &quot;jiraaction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.springexample.servicebuilder.model.impl.JIRAActionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.springexample.servicebuilder.model.impl.JIRAActionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JIRAAction
 * @see com.liferay.springexample.servicebuilder.model.impl.JIRAActionImpl
 * @see com.liferay.springexample.servicebuilder.model.impl.JIRAActionModelImpl
 * @generated
 */
@ProviderType
public interface JIRAActionModel extends BaseModel<JIRAAction> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a jira action model instance should use the {@link JIRAAction} interface instead.
	 */

	/**
	 * Returns the primary key of this jira action.
	 *
	 * @return the primary key of this jira action
	 */
	public JIRAActionPK getPrimaryKey();

	/**
	 * Sets the primary key of this jira action.
	 *
	 * @param primaryKey the primary key of this jira action
	 */
	public void setPrimaryKey(JIRAActionPK primaryKey);

	/**
	 * Returns the ID of this jira action.
	 *
	 * @return the ID of this jira action
	 */
	public long getId();

	/**
	 * Sets the ID of this jira action.
	 *
	 * @param id the ID of this jira action
	 */
	public void setId(long id);

	/**
	 * Returns the foo of this jira action.
	 *
	 * @return the foo of this jira action
	 */
	@AutoEscape
	public String getFoo();

	/**
	 * Sets the foo of this jira action.
	 *
	 * @param foo the foo of this jira action
	 */
	public void setFoo(String foo);

	/**
	 * Returns the bar of this jira action.
	 *
	 * @return the bar of this jira action
	 */
	public long getBar();

	/**
	 * Sets the bar of this jira action.
	 *
	 * @param bar the bar of this jira action
	 */
	public void setBar(long bar);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JIRAAction jiraAction);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JIRAAction> toCacheModel();

	@Override
	public JIRAAction toEscapedModel();

	@Override
	public JIRAAction toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}